# Generated by Django 4.2.16 on 2025-12-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('organism', models.CharField(max_length=255)),
                ('collection_date', models.DateField()),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('biosample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.biosample')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.metadatafield')),
            ],
            options={
                'unique_together': {('biosample', 'field')},
            },
        ),
    ]
